#!/bin/bash
if [ ! -f /usr/local/bin/composer.phar ]; then
	sudo /usr/local/bin/composer-setup
fi

if [ -n "$GITHUB_API_TOKEN" ]
then
    php /usr/local/bin/composer.phar config -g github-oauth.github.com $GITHUB_API_TOKEN
fi

exec php /usr/local/bin/composer.phar "$@"